import {
  SiApachecassandra,
  SiAmazondynamodb,
  SiInfluxdb,
  SiCouchbase,
  SiMariadb,
  SiFirebase,
  SiExpo,
  SiRender,
  SiPlatformdotsh,
  SiMysql,
  SiElasticstack,
  SiHeroku,
  SiDocker,
  SiJavascript,
  SiJirasoftware,
  SiGithub,
  SiSlack,
  SiMongodb,
  SiElasticcloud,
  SiZapier,
  SiZoom,
  SiMailchimp,
  SiNetlify,
  SiNewrelic,
  SiDigitalocean,
  SiOracle,
  SiAlibabacloud,
  SiVercel,
  SiOvh,
  SiAmazonaws,
  SiElixir,
  SiSwift,
  SiDart,
  SiRuby,
  SiKotlin,
  SiPowershell,
  SiC,
  SiHtml5,
  SiPython,
  SiRust,
  SiCplusplus,
  SiGo,
  SiPhp,
  SiMicrosoftazure,
  SiEslint,
  SiPingdom,
  SiPostgresql,
  SiRedis,
  SiRabbitmq,
  SiSentry,
  SiDatadog,
  SiAlgolia,
  SiElasticsearch,
  SiKubernetes,
  SiGooglecloud,
  SiTypescript,
  SiReact,
  SiWebpack,
  SiNodedotjs,
  SiGnubash,
  SiCss3,
  SiDiscord,
  SiAtlassian,
  SiZendesk,
  SiSupabase,
} from '@icons-pack/react-simple-icons';
import type { IconType } from '@icons-pack/react-simple-icons/types';
import type { AllowedKeys, TechItem } from '@specfy/stack-analyser';
import { listTech } from '@specfy/stack-analyser/dist/common/techs.generated';

type Extending = {
  Icon?: IconType;
  regHostname?: RegExp;
};
export type TechInfo = Extending & TechItem;

const extending: Partial<Record<AllowedKeys, Extending>> = {
  atlassian: { Icon: SiAtlassian },
  algolia: { Icon: SiAlgolia },
  alibabacloud: { Icon: SiAlibabacloud },
  'aws.dynamodb': { Icon: SiAmazondynamodb },
  'aws.s3': { Icon: SiAmazonaws },
  'aws.ec2': { Icon: SiAmazonaws },
  'aws.elasticache': { Icon: SiAmazonaws },
  'aws.glacier': { Icon: SiAmazonaws },
  'aws.lambda': { Icon: SiAmazonaws },
  'aws.rds': { Icon: SiAmazonaws },
  'aws.sns': { Icon: SiAmazonaws },
  'aws.sqs': { Icon: SiAmazonaws },
  aws: { Icon: SiAmazonaws, regHostname: /aws.amazon.com$/ },
  azure: { Icon: SiMicrosoftazure },
  'azure.ci': { Icon: SiMicrosoftazure },
  bash: { Icon: SiGnubash },
  c: { Icon: SiC },
  cassandra: { Icon: SiApachecassandra },
  couchbase: { Icon: SiCouchbase },
  cplusplus: { Icon: SiCplusplus },
  css: { Icon: SiCss3 },
  dart: { Icon: SiDart },
  datadog: { Icon: SiDatadog, regHostname: /^(www.)?datadog.com$/ },
  digitalocean: { Icon: SiDigitalocean },
  discord: { Icon: SiDiscord, regHostname: /^(www.)?discord.gg/ },
  docker: { Icon: SiDocker },
  elasticloud: { Icon: SiElasticcloud },
  elasticsearch: { Icon: SiElasticsearch },
  elasticstack: { Icon: SiElasticstack },
  elixir: { Icon: SiElixir },
  eslint: { Icon: SiEslint },
  expodev: { Icon: SiExpo },
  firebase: { Icon: SiFirebase },
  'gcp.aiplatform': { Icon: SiGooglecloud },
  'gcp.bigquery': { Icon: SiGooglecloud },
  'gcp.bigtable': { Icon: SiGooglecloud },
  'gcp.cloudbuild': { Icon: SiGooglecloud },
  'gcp.cloudrun': { Icon: SiGooglecloud },
  'gcp.dataproc': { Icon: SiGooglecloud },
  'gcp.datastore': { Icon: SiGooglecloud },
  'gcp.dns': { Icon: SiGooglecloud },
  'gcp.functions': { Icon: SiGooglecloud },
  'gcp.gce': { Icon: SiGooglecloud },
  'gcp.gcs': { Icon: SiGooglecloud },
  'gcp.gke': { Icon: SiKubernetes },
  'gcp.language': { Icon: SiGooglecloud },
  'gcp.maps': { Icon: SiGooglecloud },
  'gcp.pubsub': { Icon: SiGooglecloud },
  'gcp.secretmanager': { Icon: SiGooglecloud },
  'gcp.speech': { Icon: SiGooglecloud },
  'gcp.sql': { Icon: SiGooglecloud },
  'gcp.translate': { Icon: SiGooglecloud },
  'gcp.vision': { Icon: SiGooglecloud },
  'github.actions': { Icon: SiGithub },
  'github.pages': { Icon: SiGithub },
  gcp: { Icon: SiGooglecloud },
  github: { Icon: SiGithub, regHostname: /^(www.)?github.com$/ },
  golang: { Icon: SiGo },
  heroku: { Icon: SiHeroku },
  html: { Icon: SiHtml5 },
  influxdb: { Icon: SiInfluxdb },
  javascript: { Icon: SiJavascript },
  jira: { Icon: SiJirasoftware, regHostname: /.atlassian.net$/ },
  kotlin: { Icon: SiKotlin },
  kubernetes: { Icon: SiKubernetes },
  mailchimp: { Icon: SiMailchimp },
  mariadb: { Icon: SiMariadb },
  mongodb: { Icon: SiMongodb },
  mongodbatlas: { Icon: SiMongodb },
  mysql: { Icon: SiMysql },
  netlify: { Icon: SiNetlify, regHostname: /^(www.)?netlify.com$/ },
  newrelic: { Icon: SiNewrelic },
  nodejs: { Icon: SiNodedotjs },
  oraclecloud: { Icon: SiOracle },
  ovh: { Icon: SiOvh },
  php: { Icon: SiPhp },
  pingdom: { Icon: SiPingdom, regHostname: /^(www.)?pingdom.com$/ },
  platformsh: { Icon: SiPlatformdotsh },
  postgresql: { Icon: SiPostgresql },
  powershell: { Icon: SiPowershell },
  python: { Icon: SiPython },
  rabbitmq: { Icon: SiRabbitmq },
  react: { Icon: SiReact },
  redis: { Icon: SiRedis },
  render: { Icon: SiRender },
  ruby: { Icon: SiRuby },
  rust: { Icon: SiRust },
  sentry: { Icon: SiSentry, regHostname: /^(www.)?sentry.com$/ },
  slack: { Icon: SiSlack, regHostname: /^(www.)?slack.com$/ },
  supabase: { Icon: SiSupabase },
  'supabase.functions': { Icon: SiSupabase },
  'supabase.postgres': { Icon: SiSupabase },
  'supabase.storage': { Icon: SiSupabase },
  swift: { Icon: SiSwift },
  typescript: { Icon: SiTypescript },
  vercel: { Icon: SiVercel },
  webpack: { Icon: SiWebpack },
  zapier: { Icon: SiZapier, regHostname: /^(www.)?zapier.com$/ },
  zendesk: { Icon: SiZendesk },
  zoom: { Icon: SiZoom },
};

export const supportedArray: TechInfo[] = listTech.map((t) => {
  if (t.key in extending) {
    return { ...t, ...extending[t.key] };
  }
  return t;
});

export const supportedIndexed: Record<string, TechInfo> = {};
Object.values(supportedArray).forEach((v) => {
  supportedIndexed[v.key] = v;
});

export const supportedHostname = supportedArray.filter((i) => i.regHostname);
