import {
  SiApachecassandra,
  SiAmazondynamodb,
  SiInfluxdb,
  SiCouchbase,
  SiMariadb,
  SiFirebase,
  SiExpo,
  SiRender,
  SiPlatformdotsh,
  SiMysql,
  SiElasticstack,
  SiHeroku,
  SiDocker,
  SiJavascript,
  SiJirasoftware,
  SiGithub,
  SiSlack,
  SiMongodb,
  SiElasticcloud,
  SiZapier,
  SiZoom,
  SiMailchimp,
  SiNetlify,
  SiNewrelic,
  SiDigitalocean,
  SiOracle,
  SiAlibabacloud,
  SiVercel,
  SiOvh,
  SiAmazonaws,
  SiElixir,
  SiSwift,
  SiDart,
  SiRuby,
  SiKotlin,
  SiPowershell,
  SiC,
  SiHtml5,
  SiPython,
  SiRust,
  SiCplusplus,
  SiGo,
  SiPhp,
  SiMicrosoftazure,
  SiEslint,
  SiPingdom,
  SiPostgresql,
  SiRedis,
  SiRabbitmq,
  SiSentry,
  SiDatadog,
  SiAlgolia,
  SiElasticsearch,
  SiKubernetes,
  SiGooglecloud,
  SiTypescript,
  SiReact,
  SiWebpack,
  SiNodedotjs,
  SiGnubash,
  SiCss3,
  SiDiscord,
  SiAtlassian,
  SiZendesk,
  SiSupabase,
  SiAuth0,
  SiOpenai,
  SiStripe,
  SiNotion,
  SiPostman,
  SiFigma,
  SiGrafana,
  SiSquarespace,
  SiTwilio,
  SiAirtable,
  SiAdobe,
  SiShopify,
  SiHubspot,
  SiPlausibleanalytics,
  SiAirbyte,
  SiCircleci,
  SiCirrusci,
  SiCypress,
  SiGitlab,
  SiGoogleanalytics,
  SiKibana,
  SiNginx,
  SiDependabot,
  SiRenovatebot,
  SiApacheairflow,
  SiApachekafka,
  SiApachecouchdb,
  SiSqlite,
  SiCloudflare,
  SiClickhouse,
  SiUpstash,
  SiScaleway,
  SiSendinblue,
  SiContentful,
  SiHotjar,
} from '@icons-pack/react-simple-icons';
import type { IconType } from '@icons-pack/react-simple-icons/types';
import type { AllowedKeys, TechItem } from '@specfy/stack-analyser';
import { listTech } from '@specfy/stack-analyser/dist/common/techs.generated';

type Extending = {
  Icon?: IconType;
  regHostname?: RegExp;
};
export type TechInfo = Extending & TechItem;

const extending: Partial<Record<AllowedKeys, Extending>> = {
  adobe: { Icon: SiAdobe },
  airbyte: { Icon: SiAirbyte },
  airtable: { Icon: SiAirtable },
  algolia: { Icon: SiAlgolia },
  alibabacloud: { Icon: SiAlibabacloud },
  apache_cassandra: { Icon: SiApachecassandra },
  apache_airflow: { Icon: SiApacheairflow },
  apache_kafka: { Icon: SiApachekafka },
  apache_couchdb: { Icon: SiApachecouchdb },
  atlassian: { Icon: SiAtlassian },
  auth0: { Icon: SiAuth0 },
  'aws.dynamodb': { Icon: SiAmazondynamodb },
  'aws.s3': { Icon: SiAmazonaws },
  'aws.ec2': { Icon: SiAmazonaws },
  'aws.elasticache': { Icon: SiAmazonaws },
  'aws.glacier': { Icon: SiAmazonaws },
  'aws.lambda': { Icon: SiAmazonaws },
  'aws.rds': { Icon: SiAmazonaws },
  'aws.sns': { Icon: SiAmazonaws },
  'aws.sqs': { Icon: SiAmazonaws },
  'aws.amplify_hosting': { Icon: SiAmazonaws },
  'aws.ecs': { Icon: SiAmazonaws },
  'aws.fargate': { Icon: SiAmazonaws },
  aws: { Icon: SiAmazonaws, regHostname: /aws.amazon.com$/ },
  azure: { Icon: SiMicrosoftazure },
  'azure.ci': { Icon: SiMicrosoftazure },
  bash: { Icon: SiGnubash },
  brevo: { Icon: SiSendinblue },
  c: { Icon: SiC },
  circleci: { Icon: SiCircleci },
  cirrusci: { Icon: SiCirrusci },
  cloudflare: { Icon: SiCloudflare },
  clickhouse: { Icon: SiClickhouse },
  contenful: { Icon: SiContentful },
  couchbase: { Icon: SiCouchbase },
  cplusplus: { Icon: SiCplusplus },
  css: { Icon: SiCss3 },
  cypressci: { Icon: SiCypress },
  dart: { Icon: SiDart },
  datadog: { Icon: SiDatadog, regHostname: /^(www.)?datadog.com$/ },
  dependabot: { Icon: SiDependabot },
  digitalocean: { Icon: SiDigitalocean },
  discord: { Icon: SiDiscord, regHostname: /^(www.)?discord.gg/ },
  docker: { Icon: SiDocker },
  elasticloud: { Icon: SiElasticcloud },
  elasticsearch: { Icon: SiElasticsearch },
  elasticstack: { Icon: SiElasticstack },
  elixir: { Icon: SiElixir },
  eslint: { Icon: SiEslint },
  expodev: { Icon: SiExpo },
  figma: { Icon: SiFigma },
  firebase: { Icon: SiFirebase },
  'firebase.firestore': { Icon: SiFirebase },
  'gcp.aiplatform': { Icon: SiGooglecloud },
  'gcp.bigquery': { Icon: SiGooglecloud },
  'gcp.bigtable': { Icon: SiGooglecloud },
  'gcp.cloudbuild': { Icon: SiGooglecloud },
  'gcp.cloudrun': { Icon: SiGooglecloud },
  'gcp.dataproc': { Icon: SiGooglecloud },
  'gcp.datastore': { Icon: SiGooglecloud },
  'gcp.dns': { Icon: SiGooglecloud },
  'gcp.functions': { Icon: SiGooglecloud },
  'gcp.gce': { Icon: SiGooglecloud },
  'gcp.gcs': { Icon: SiGooglecloud },
  'gcp.gke': { Icon: SiKubernetes },
  'gcp.language': { Icon: SiGooglecloud },
  'gcp.maps': { Icon: SiGooglecloud },
  'gcp.pubsub': { Icon: SiGooglecloud },
  'gcp.secretmanager': { Icon: SiGooglecloud },
  'gcp.speech': { Icon: SiGooglecloud },
  'gcp.sql': { Icon: SiGooglecloud },
  'gcp.translate': { Icon: SiGooglecloud },
  'gcp.vision': { Icon: SiGooglecloud },
  'gcp.dataflow': { Icon: SiGooglecloud },
  'gcp.dialogflow': { Icon: SiGooglecloud },
  'gcp.kms': { Icon: SiGooglecloud },
  'gcp.memorystore': { Icon: SiGooglecloud },
  'gcp.spanner': { Icon: SiGooglecloud },
  'gcp.tasks': { Icon: SiGooglecloud },
  'github.actions': { Icon: SiGithub },
  'github.pages': { Icon: SiGithub },
  gcp: { Icon: SiGooglecloud },
  github: { Icon: SiGithub, regHostname: /^(www.)?github.com$/ },
  gitlab: { Icon: SiGitlab },
  'gitlab.ci': { Icon: SiGitlab },
  golang: { Icon: SiGo },
  googleanalytics: { Icon: SiGoogleanalytics },
  grafana: { Icon: SiGrafana },
  heroku: { Icon: SiHeroku },
  hotjar: { Icon: SiHotjar },
  hubspot: { Icon: SiHubspot },
  html: { Icon: SiHtml5 },
  influxdb: { Icon: SiInfluxdb },
  javascript: { Icon: SiJavascript },
  jira: { Icon: SiJirasoftware, regHostname: /.atlassian.net$/ },
  kibana: { Icon: SiKibana },
  kotlin: { Icon: SiKotlin },
  kubernetes: { Icon: SiKubernetes },
  mailchimp: { Icon: SiMailchimp },
  mariadb: { Icon: SiMariadb },
  mongodb: { Icon: SiMongodb },
  mongodbatlas: { Icon: SiMongodb },
  mysql: { Icon: SiMysql },
  netlify: { Icon: SiNetlify, regHostname: /^(www.)?netlify.com$/ },
  newrelic: { Icon: SiNewrelic },
  nginx: { Icon: SiNginx },
  nodejs: { Icon: SiNodedotjs },
  notion: { Icon: SiNotion },
  openai: { Icon: SiOpenai },
  oraclecloud: { Icon: SiOracle },
  ovh: { Icon: SiOvh },
  php: { Icon: SiPhp },
  pingdom: { Icon: SiPingdom, regHostname: /^(www.)?pingdom.com$/ },
  platformsh: { Icon: SiPlatformdotsh },
  plausible: { Icon: SiPlausibleanalytics },
  postgresql: { Icon: SiPostgresql },
  postman: { Icon: SiPostman },
  powershell: { Icon: SiPowershell },
  python: { Icon: SiPython },
  rabbitmq: { Icon: SiRabbitmq },
  react: { Icon: SiReact },
  redis: { Icon: SiRedis },
  render: { Icon: SiRender },
  renovate: { Icon: SiRenovatebot },
  ruby: { Icon: SiRuby },
  rust: { Icon: SiRust },
  scaleway: { Icon: SiScaleway },
  sendgrid: { Icon: SiTwilio },
  sentry: { Icon: SiSentry, regHostname: /^(www.)?sentry.com$/ },
  shopify: { Icon: SiShopify },
  slack: { Icon: SiSlack, regHostname: /^(www.)?slack.com$/ },
  squarespace: { Icon: SiSquarespace },
  sqlite: { Icon: SiSqlite },
  stripe: { Icon: SiStripe },
  supabase: { Icon: SiSupabase },
  'supabase.functions': { Icon: SiSupabase },
  'supabase.postgres': { Icon: SiSupabase },
  'supabase.storage': { Icon: SiSupabase },
  swift: { Icon: SiSwift },
  typescript: { Icon: SiTypescript },
  twilio: { Icon: SiTwilio },
  upstash: { Icon: SiUpstash },
  'upstash.kafka': { Icon: SiUpstash },
  'upstash.qstash': { Icon: SiUpstash },
  'upstash.redis': { Icon: SiUpstash },
  vercel: { Icon: SiVercel },
  'vercel.ai': { Icon: SiVercel },
  'vercel.analytics': { Icon: SiVercel },
  'vercel.blob': { Icon: SiVercel },
  'vercel.kv': { Icon: SiVercel },
  'vercel.postgres': { Icon: SiVercel },
  webpack: { Icon: SiWebpack },
  zapier: { Icon: SiZapier, regHostname: /^(www.)?zapier.com$/ },
  zendesk: { Icon: SiZendesk },
  zoom: { Icon: SiZoom },
};

export const supportedArray: TechInfo[] = listTech.map((t) => {
  if (t.key in extending) {
    return { ...t, ...extending[t.key] };
  }
  return t;
});

export const supportedIndexed: Record<string, TechInfo> = {};
Object.values(supportedArray).forEach((v) => {
  supportedIndexed[v.key] = v;
});

export const supportedHostname = supportedArray.filter((i) => i.regHostname);
