# docker-compose.yml
version: '3'
services:
  db:
    container_name: db
    image: postgres:15.5-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres

  es:
    container_name: es
    image: elasticsearch:8.11.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  esdata1:
    driver: local
