const t = [
  {
    id: 'TgeRVEorHURP',
    name: 'algolia-crawler',
    group: 'component',
    path: ['/Users/samuelbodin/code/crawler/package.json'],
    tech: null,
    edges: [],
    inComponent: null,
    childs: [
      {
        id: 'LKAUhA7UKaAU',
        name: '@algolia/crawler-admin',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-admin/package.json',
        ],
        tech: null,
        edges: [
          {
            to: 'sD2b1kBpdR3M',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: '5vPu7sfrXUFB',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'sD2b1kBpdR3M',
            name: 'algolia',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-admin/package.json',
            ],
            tech: 'algolia',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: '5vPu7sfrXUFB',
            name: 'sentry',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-admin/package.json',
            ],
            tech: 'sentry',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: [
          'algolia',
          'eslint',
          'express',
          'html',
          'javascript',
          'nodejs',
          'prettier',
          'react',
          'scss',
          'sentry',
          'storybook',
          'typescript',
          'webpack',
        ],
        languages: {
          JavaScript: 9,
          Markdown: 1,
          JSON: 2,
          TypeScript: 462,
          SCSS: 96,
          SVG: 11,
          HTML: 1,
        },
        dependencies: [
          ['npm', '@algolia/client-search', '4.14.2'],
          ['npm', '@algolia/crawler-api', '1.0.0'],
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-external-data', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@algolia/crawler-tests', '1.0.0'],
          ['npm', '@algolia/json-stream-analyzer', '0.2.17'],
          ['npm', '@algolia/satellite', '1.0.0-beta.133'],
          ['npm', '@babel/core', '7.18.10'],
          ['npm', '@babel/plugin-proposal-class-properties', '7.18.6'],
          ['npm', '@babel/plugin-proposal-decorators', '7.18.10'],
          [
            'npm',
            '@babel/plugin-proposal-nullish-coalescing-operator',
            '7.18.6',
          ],
          ['npm', '@babel/plugin-proposal-optional-chaining', '7.18.9'],
          ['npm', '@babel/polyfill', '7.12.1'],
          ['npm', '@babel/preset-env', '7.18.10'],
          ['npm', '@babel/preset-react', '7.18.6'],
          ['npm', '@babel/preset-typescript', '7.18.6'],
          ['npm', '@docsearch/css', '3.2.1'],
          ['npm', '@docsearch/react', '3.2.1'],
          ['npm', '@google-cloud/storage', '6.0.1'],
          ['npm', '@sentry/browser', '7.11.1'],
          ['npm', '@sentry/cli', '2.5.2'],
          ['npm', '@size-limit/preset-small-lib', '6.0.3'],
          ['npm', '@storybook/addon-a11y', '6.5.10'],
          ['npm', '@storybook/addon-actions', '6.5.10'],
          ['npm', '@storybook/addon-knobs', '6.4.0'],
          ['npm', '@storybook/addon-storysource', '6.5.10'],
          ['npm', '@storybook/addon-viewport', '6.5.10'],
          ['npm', '@storybook/react', '6.5.10'],
          ['npm', '@storybook/source-loader', '6.5.10'],
          ['npm', '@testing-library/react', '12.1.5'],
          ['npm', '@types/classnames', '2.3.0'],
          ['npm', '@types/esprima', '4.0.3'],
          ['npm', '@types/estree', '1.0.0'],
          ['npm', '@types/jest', '28.1.7'],
          ['npm', '@types/md5', '2.3.2'],
          ['npm', '@types/node', '16.11.48'],
          ['npm', '@types/qs', '6.9.7'],
          ['npm', '@types/react', '17.0.48'],
          ['npm', '@types/react-dom', '18.0.6'],
          ['npm', '@types/react-infinite-scroller', '1.2.3'],
          ['npm', '@types/react-input-autosize', '2.2.1'],
          ['npm', '@types/react-router', '5.1.18'],
          ['npm', '@types/react-router-dom', '5.3.3'],
          ['npm', '@types/react-sticky-el', '1.0.3'],
          ['npm', '@types/react-transition-group', '4.4.5'],
          ['npm', '@types/reactstrap', '8.7.1'],
          ['npm', '@typescript-eslint/eslint-plugin', '5.20.0'],
          ['npm', '@typescript-eslint/parser', '5.20.0'],
          ['npm', 'algoliasearch', '4.14.2'],
          ['npm', 'array-move', '4.0.0'],
          ['npm', 'autoprefixer', '10.4.8'],
          ['npm', 'babel-loader', '8.2.5'],
          ['npm', 'babel-preset-react-app', '10.0.1'],
          ['npm', 'classnames', '2.3.1'],
          ['npm', 'clean-webpack-plugin', '4.0.0'],
          ['npm', 'console-feed', '3.3.0'],
          ['npm', 'core-js', '3.24.1'],
          ['npm', 'css-loader', '5.2.7'],
          ['npm', 'dotenv', '16.0.1'],
          ['npm', 'dotenv-webpack', '8.0.1'],
          ['npm', 'downshift', '6.1.9'],
          ['npm', 'eslint', '7.32.0'],
          ['npm', 'eslint-config-prettier', '8.5.0'],
          ['npm', 'eslint-plugin-import', '2.26.0'],
          ['npm', 'eslint-plugin-jsx-a11y', '6.6.1'],
          ['npm', 'eslint-plugin-prettier', '4.2.1'],
          ['npm', 'eslint-plugin-react', '7.30.1'],
          ['npm', 'eslint-plugin-react-hooks', '4.6.0'],
          ['npm', 'esprima', '4.0.1'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'file-loader', '6.2.0'],
          ['npm', 'fuse.js', '6.6.2'],
          ['npm', 'helmet', '5.0.2'],
          ['npm', 'history', '4.10.1'],
          ['npm', 'html-webpack-plugin', '5.5.0'],
          ['npm', 'humanize-duration', '3.27.2'],
          ['npm', 'jest-environment-jsdom', '28.1.3'],
          ['npm', 'later', '1.2.0'],
          ['npm', 'md5', '2.3.0'],
          ['npm', 'mini-css-extract-plugin', '2.6.1'],
          ['npm', 'mobx', '6.6.1'],
          ['npm', 'mobx-react', '7.5.2'],
          ['npm', 'mobx-remotedev', '0.3.6'],
          ['npm', 'moment', '2.29.4'],
          ['npm', 'monaco-editor', '0.31.1'],
          ['npm', 'monaco-editor-webpack-plugin', '7.0.1'],
          ['npm', 'node-sass', '7.0.1'],
          ['npm', 'null-loader', '4.0.1'],
          ['npm', 'p-limit', '4.0.0'],
          ['npm', 'postcss', '8.3.7'],
          ['npm', 'postcss-clean', '1.2.2'],
          ['npm', 'postcss-loader', '7.0.1'],
          ['npm', 'postcss-normalize', '10.0.1'],
          ['npm', 'postcss-preset-env', '6.7.1'],
          ['npm', 'postcss-scss', '4.0.4'],
          ['npm', 'prettier', '2.6.2'],
          ['npm', 'process', '0.11.10'],
          ['npm', 'purgecss', '4.1.3'],
          ['npm', 'qs', '6.11.0'],
        ],
      },
      {
        id: 'QoneRfDgcVoV',
        name: '@algolia/crawler-api',
        group: 'component',
        path: ['/Users/samuelbodin/code/crawler/src/crawler-api/package.json'],
        tech: null,
        edges: [
          {
            to: 'OrDMlr7XstB9',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'OrDMlr7XstB9',
            name: 'redis',
            group: 'component',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-api/package.json',
            ],
            tech: 'redis',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['express', 'javascript', 'nodejs', 'redis', 'typescript'],
        languages: { JSON: 3, YAML: 2, TypeScript: 83, JavaScript: 1 },
        dependencies: [
          ['npm', '@algolia/crawler-api-public', '1.0.0'],
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@algolia/crawler-worker', '1.0.0'],
          ['npm', 'body-parser', '1.20.0'],
          ['npm', 'cidr-matcher', '2.1.1'],
          ['npm', 'connect-redis', '6.1.3'],
          ['npm', 'cookie-parser', '1.4.6'],
          ['npm', 'cors', '2.8.5'],
          ['npm', 'csurf', '1.11.0'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'express-session', '1.17.3'],
          ['npm', 'http-proxy-middleware', '2.0.6'],
          ['npm', 'nocache', '3.0.4'],
          ['npm', 'passport', '0.6.0'],
          ['npm', 'passport-http', '0.3.0'],
          ['npm', 'passport-oauth2', '1.6.1'],
          ['npm', 'passport-trusted-header', '1.1.0'],
          ['npm', 'rate-limiter-flexible', '2.3.8'],
          ['npm', 'redis', '3.1.2'],
          ['npm', '@types/connect-redis', '0.0.18'],
          ['npm', '@types/cors', '2.8.12'],
          ['npm', '@types/csurf', '1.11.2'],
          ['npm', '@types/express', '4.17.13'],
          ['npm', '@types/express-session', '1.17.4'],
          ['npm', '@types/helmet', '0.0.48'],
          ['npm', '@types/passport', '1.0.10'],
          ['npm', '@types/passport-oauth2', '1.4.11'],
          ['npm', '@types/redis', '2.8.32'],
          ['npm', 'dotenv', '16.0.1'],
          ['npm', 'swagger-jsdoc', '6.2.5'],
          ['npm', 'swagger-markdown', '1.4.6'],
        ],
      },
      {
        id: 'EcYTCcXLpcap',
        name: '@algolia/crawler-api-public',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-api-public/package.json',
        ],
        tech: null,
        edges: [
          {
            to: '2qYG8n1tNuxz',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: '2qYG8n1tNuxz',
            name: 'redis',
            group: 'component',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-api-public/package.json',
            ],
            tech: 'redis',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['express', 'nodejs', 'redis', 'typescript'],
        languages: { JSON: 2, Markdown: 1, YAML: 3, TypeScript: 36 },
        dependencies: [
          ['npm', '@algolia/crawler-api', '1.0.0'],
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@algolia/crawler-manager', '1.0.0'],
          ['npm', '@algolia/crawler-worker', '1.0.0'],
          ['npm', 'altheia-async-data-validator', '5.0.15'],
          ['npm', 'body-parser', '1.20.0'],
          ['npm', 'cors', '2.8.5'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'passport', '0.6.0'],
          ['npm', 'passport-http', '0.3.0'],
          ['npm', 'rate-limiter-flexible', '2.3.8'],
          ['npm', 'redis', '3.1.2'],
          ['npm', 'swagger-ui-express', '4.3.0'],
          ['npm', 'yamljs', '0.3.0'],
          ['npm', '@types/passport-http', '0.3.9'],
          ['npm', '@types/swagger-ui-express', '4.1.3'],
        ],
      },
      {
        id: 'iRJTgSu5IQwn',
        name: '@algolia/crawler-auditlogs',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-auditlogs/package.json',
        ],
        tech: null,
        edges: [],
        inComponent: null,
        childs: [],
        techs: ['nodejs', 'typescript'],
        languages: { JSON: 2, TypeScript: 6 },
        dependencies: [
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@google-cloud/pubsub', '3.0.1'],
        ],
      },
      {
        id: '0xCF6pM9OwpO',
        name: '@algolia/crawler-common',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-common/package.json',
        ],
        tech: null,
        edges: [
          {
            to: '9uqAp4UPWDNQ',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'ktoTySOgQtW8',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'HJtJo3LWjOho',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'jsHmJJQIrNp8',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'Y6ll3y0eDLYJ',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'xOL1HoFhFs9g',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'taqb2iyjDX06',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'HJtJo3LWjOho',
            name: 'algolia',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-common/package.json',
            ],
            tech: 'algolia',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: '9uqAp4UPWDNQ',
            name: 'elasticsearch',
            group: 'component',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-common/package.json',
            ],
            tech: 'elasticsearch',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: 'Y6ll3y0eDLYJ',
            name: 'mailjet',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-common/package.json',
            ],
            tech: 'mailjet',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: 'xOL1HoFhFs9g',
            name: 'postgresql',
            group: 'component',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-common/package.json',
            ],
            tech: 'postgresql',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: 'jsHmJJQIrNp8',
            name: 'rabbitmq',
            group: 'component',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-common/package.json',
            ],
            tech: 'rabbitmq',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: 'ktoTySOgQtW8',
            name: 'sentry',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-common/package.json',
            ],
            tech: 'sentry',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: 'taqb2iyjDX06',
            name: 'sqreen',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-common/package.json',
            ],
            tech: 'sqreen',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: [
          'algolia',
          'elasticsearch',
          'eslint',
          'express',
          'mailjet',
          'nodejs',
          'postgresql',
          'rabbitmq',
          'sentry',
          'sqreen',
          'typescript',
        ],
        languages: {
          JSON: 3,
          TypeScript: 321,
          'Jest Snapshot': 10,
          Handlebars: 8,
        },
        dependencies: [
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@algolia/crawler-manager', '1.0.0'],
          ['npm', '@algolia/crawler-tests', '1.0.0'],
          ['npm', '@algolia/crawler-worker', '1.0.0'],
          ['npm', '@algolia/json-stream-analyzer', '0.2.17'],
          ['npm', '@algolia/requester-node-http', '4.14.2'],
          ['npm', '@algolia/transporter', '4.14.2'],
          ['npm', '@elastic/elasticsearch', '7.17.0'],
          ['npm', '@google-cloud/error-reporting', '3.0.1'],
          ['npm', '@sentry/node', '7.11.1'],
          ['npm', 'ajv', '8.11.0'],
          ['npm', 'algoliasearch', '4.14.2'],
          ['npm', 'altheia-async-data-validator', '5.0.15'],
          ['npm', 'amqplib', '0.8.0'],
          ['npm', 'bcrypt', '5.0.1'],
          ['npm', 'bunyan', '1.8.15'],
          ['npm', 'bunyan-debug-stream', '2.0.1'],
          ['npm', 'content-type', '1.0.4'],
          ['npm', 'crc-32', '1.2.2'],
          ['npm', 'csv-parse', '5.0.4'],
          ['npm', 'diff', '5.0.0'],
          ['npm', 'eslint', '7.32.0'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'handlebars', '4.7.7'],
          ['npm', 'hot-shots', '9.2.0'],
          ['npm', 'json-stable-stringify', '1.0.1'],
          ['npm', 'knex', '2.0.0'],
          ['npm', 'later', '1.2.0'],
          ['npm', 'limiter', '2.1.0'],
          ['npm', 'micromatch', '4.0.5'],
          ['npm', 'mjml', '4.12.0'],
          ['npm', 'module-alias', '2.2.2'],
          ['npm', 'moment', '2.29.4'],
          ['npm', 'mv', '2.1.1'],
          ['npm', 'node-fetch', '2.6.7'],
          ['npm', 'node-mailjet', '5.0.1'],
          ['npm', 'pg', '8.7.3'],
          ['npm', 'pg-format', '1.0.4'],
          ['npm', 'request', '2.88.2'],
          ['npm', 'request-promise-native', '1.0.9'],
          ['npm', 'robots-parser', '3.0.0'],
          ['npm', 'sodium-native', '3.3.0'],
          ['npm', 'sq-native', '1.0.10'],
          ['npm', 'sqreen', '2.0.1'],
          ['npm', '@algolia/client-common', '4.14.2'],
          ['npm', '@algolia/client-search', '4.14.2'],
          ['npm', '@algolia/requester-common', '4.14.2'],
          ['npm', '@sinonjs/fake-timers', '9.1.2'],
          ['npm', '@types/amqplib', '0.8.2'],
          ['npm', '@types/bcrypt', '5.0.0'],
          ['npm', '@types/bunyan', '1.8.8'],
          ['npm', '@types/content-type', '1.1.5'],
          ['npm', '@types/eslint', '7.29.0'],
          ['npm', '@types/json-stable-stringify', '1.0.34'],
          ['npm', '@types/later', '1.2.7'],
          ['npm', '@types/mjml', '4.7.0'],
          ['npm', '@types/node-fetch', '2.6.2'],
          ['npm', '@types/node-mailjet', '3.3.9'],
          ['npm', '@types/pg', '8.6.5'],
          ['npm', '@types/pg-format', '1.0.2'],
          ['npm', '@types/request', '2.48.8'],
          ['npm', '@types/request-promise-native', '1.0.18'],
          ['npm', '@types/sinonjs__fake-timers', '8.1.2'],
          ['npm', '@types/sodium-native', '2.3.5'],
          ['npm', 'benny', '3.7.1'],
          ['npm', 'dotenv', '16.0.1'],
          ['npm', 'google-auth-library', '8.3.0'],
          ['npm', 'nock', '13.2.9'],
          ['npm', 'ora', '5.4.1'],
          ['npm', 'ts-jest', '28.0.8'],
        ],
      },
      {
        id: 'FdgSgTibRitC',
        name: '@algolia/crawler-cron',
        group: 'component',
        path: ['/Users/samuelbodin/code/crawler/src/crawler-cron/package.json'],
        tech: null,
        edges: [],
        inComponent: null,
        childs: [],
        techs: ['nodejs', 'typescript'],
        languages: { JSON: 2, TypeScript: 26, 'Jest Snapshot': 1 },
        dependencies: [
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@slack/web-api', '6.7.2'],
          ['npm', 'moment', '2.29.4'],
        ],
      },
      {
        id: 'kEu3BYkhiNL5',
        name: '@algolia/crawler-cypress',
        group: 'component',
        path: ['/Users/samuelbodin/code/crawler/cypress/package.json'],
        tech: null,
        edges: [
          {
            to: 'bqzefi2ndeBM',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'bqzefi2ndeBM',
            name: 'algolia',
            group: 'thirdparty',
            path: ['/Users/samuelbodin/code/crawler/cypress/package.json'],
            tech: 'algolia',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['algolia', 'cypressci', 'eslint', 'javascript', 'nodejs'],
        languages: { JSON: 3, JavaScript: 15, XML: 4 },
        dependencies: [
          ['npm', 'module-alias', '2.2.2'],
          ['npm', 'algoliasearch', '4.14.2'],
          ['npm', 'cypress', '8.7.0'],
          ['npm', 'cypress-log-to-output', '1.1.2'],
          ['npm', 'cypress-multi-reporters', '1.6.1'],
          ['npm', 'dotenv', '16.0.1'],
          ['npm', 'junit', '1.4.9'],
          ['npm', 'mocha', '10.0.0'],
          ['npm', 'mocha-junit-reporter', '2.0.2'],
          ['npm', 'uuid', '8.3.2'],
        ],
      },
      {
        id: 'IlXZ4AuaMp34',
        name: '@algolia/crawler-external-data',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-external-data/package.json',
        ],
        tech: null,
        edges: [],
        inComponent: null,
        childs: [],
        techs: ['express', 'nodejs', 'typescript'],
        languages: { JSON: 2, TypeScript: 40, 'Jest Snapshot': 1 },
        dependencies: [
          ['npm', '@adobe/aio-lib-analytics', '3.0.0'],
          ['npm', '@adobe/jwt-auth', '1.0.1'],
          ['npm', '@algolia/crawler-api', '1.0.0'],
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@google-cloud/storage', '6.0.1'],
          ['npm', '@googleapis/analytics', '2.0.0'],
          ['npm', '@googleapis/analyticsreporting', '0.3.0'],
          ['npm', '@googleapis/oauth2', '0.3.1'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'module-alias', '2.2.2'],
          ['npm', 'node-fetch', '2.6.7'],
          ['npm', '@types/adobe__aio-lib-analytics', '2.1.0'],
          ['npm', '@types/module-alias', '2.0.1'],
        ],
      },
      {
        id: 'ZWQHBbeNDHLr',
        name: '@algolia/crawler-isolated',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-isolated/package.json',
        ],
        tech: null,
        edges: [],
        inComponent: null,
        childs: [],
        techs: ['javascript', 'nodejs', 'prettier', 'typescript', 'webpack'],
        languages: {
          Markdown: 1,
          JSON: 2,
          TypeScript: 82,
          'Jest Snapshot': 14,
          JavaScript: 2,
        },
        dependencies: [
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', 'isolated-vm', '4.3.7'],
          ['npm', 'prettier', '2.6.2'],
          ['npm', 'tosource', '1.0.0'],
          ['npm', '@algolia/crawler-tests', '1.0.0'],
          ['npm', '@babel/core', '7.18.10'],
          ['npm', '@babel/plugin-proposal-class-properties', '7.18.6'],
          [
            'npm',
            '@babel/plugin-proposal-nullish-coalescing-operator',
            '7.18.6',
          ],
          ['npm', '@babel/plugin-proposal-optional-chaining', '7.18.9'],
          ['npm', '@babel/plugin-proposal-private-methods', '7.18.6'],
          [
            'npm',
            '@babel/plugin-proposal-private-property-in-object',
            '7.18.6',
          ],
          ['npm', '@babel/preset-typescript', '7.18.6'],
          ['npm', '@types/micromatch', '4.0.2'],
          ['npm', '@types/prettier', '2.6.3'],
          ['npm', '@types/webpack-env', '1.18.0'],
          ['npm', 'babel-loader', '8.2.5'],
          ['npm', 'benny', '3.7.1'],
          ['npm', 'buffer', '6.0.3'],
          ['npm', 'cheerio', '1.0.0-rc.10'],
          ['npm', 'clean-webpack-plugin', '4.0.0'],
          ['npm', 'core-js', '3.24.1'],
          ['npm', 'domhandler', '4.2.0'],
          ['npm', 'fastestsmallesttextencoderdecoder', '1.0.22'],
          ['npm', 'micromatch', '4.0.5'],
          ['npm', 'path-browserify', '1.0.1'],
          ['npm', 'process', '0.11.10'],
          ['npm', 'schema-dts', '1.1.0'],
          ['npm', 'terser-webpack-plugin', '5.3.5'],
          ['npm', 'url', '0.11.0'],
          ['npm', 'util', '0.12.4'],
          ['npm', 'webpack', '5.74.0'],
          ['npm', 'webpack-cli', '4.10.0'],
        ],
      },
      {
        id: 'Looppx2a9QDG',
        name: '@algolia/crawler-local-setup',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-local-setup/package.json',
        ],
        tech: null,
        edges: [],
        inComponent: null,
        childs: [],
        techs: ['express', 'javascript', 'nodejs', 'typescript'],
        languages: { JSON: 3, TypeScript: 4, JavaScript: 6 },
        dependencies: [
          ['npm', '@algolia/crawler-api', '1.0.0'],
          ['npm', '@algolia/crawler-api-public', '1.0.0'],
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@algolia/crawler-manager', '1.0.0'],
          ['npm', '@algolia/crawler-test-website', '1.0.0'],
          ['npm', '@algolia/crawler-tests', '1.0.0'],
          ['npm', '@algolia/crawler-worker', '1.0.0'],
          ['npm', 'express', '4.17.3'],
        ],
      },
      {
        id: 'cdOQbwd9LGeO',
        name: '@algolia/crawler-manager',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-manager/package.json',
        ],
        tech: null,
        edges: [
          {
            to: 'UvKKEdwYiLRo',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'Wi1hMXIkclnG',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'Wi1hMXIkclnG',
            name: 'algolia',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-manager/package.json',
            ],
            tech: 'algolia',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: 'UvKKEdwYiLRo',
            name: 'datadog',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-manager/package.json',
            ],
            tech: 'datadog',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['algolia', 'datadog', 'nodejs', 'typescript'],
        languages: { JSON: 2, TypeScript: 27 },
        dependencies: [
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', 'dd-trace', '3.0.0'],
          ['npm', '@algolia/client-search', '4.14.2'],
          ['npm', '@algolia/crawler-tests', '1.0.0'],
          ['npm', '@algolia/transporter', '4.14.2'],
          ['npm', 'dotenv', '16.0.1'],
          ['npm', 'hot-shots', '9.2.0'],
        ],
      },
      {
        id: '9qq8V8sybGli',
        name: '@algolia/crawler-scripts',
        group: 'component',
        path: ['/Users/samuelbodin/code/crawler/scripts/package.json'],
        tech: null,
        edges: [
          {
            to: 'dHSDZiODierY',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'dHSDZiODierY',
            name: 'algolia',
            group: 'thirdparty',
            path: ['/Users/samuelbodin/code/crawler/scripts/package.json'],
            tech: 'algolia',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['algolia', 'javascript', 'nodejs', 'shell', 'typescript'],
        languages: {
          JavaScript: 13,
          TypeScript: 37,
          Shell: 27,
          Markdown: 1,
          JSON: 25,
          'Jest Snapshot': 1,
        },
        dependencies: [
          ['npm', 'module-alias', '2.2.2'],
          ['npm', '@google-cloud/bigquery', '6.0.2'],
          ['npm', '@octokit/rest', '19.0.4'],
          ['npm', '@slack/client', '5.0.2'],
          ['npm', '@types/csv-stringify', '3.1.0'],
          ['npm', '@types/yargs', '17.0.11'],
          ['npm', 'algoliasearch', '4.14.2'],
          ['npm', 'bunyan', '1.8.15'],
          ['npm', 'chalk', '4.1.2'],
          ['npm', 'conventional-commits-parser', '3.2.4'],
          ['npm', 'csv-stringify', '6.2.0'],
          ['npm', 'dotenv', '16.0.1'],
          ['npm', 'json', '11.0.0'],
          ['npm', 'micromatch', '4.0.5'],
          ['npm', 'node-fetch', '2.6.7'],
          ['npm', 'ora', '5.4.1'],
          ['npm', 'p-limit', '4.0.0'],
          ['npm', 'semantic-release', '19.0.3'],
          ['npm', 'sodium-native', '3.3.0'],
          ['npm', 'ts-node', '10.9.1'],
          ['npm', 'yargs', '17.5.1'],
        ],
      },
      {
        id: 'rjiySzaZm26h',
        name: '@algolia/crawler-spec',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-integration-tests/package.json',
        ],
        tech: null,
        edges: [
          {
            to: 'w56tQ5HYcdJK',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'w56tQ5HYcdJK',
            name: 'algolia',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-integration-tests/package.json',
            ],
            tech: 'algolia',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['algolia', 'express', 'nodejs', 'typescript'],
        languages: { JSON: 2, 'Jest Snapshot': 6, TypeScript: 56 },
        dependencies: [
          ['npm', '@algolia/client-search', '4.14.2'],
          ['npm', '@algolia/crawler-external-data', '1.0.0'],
          ['npm', '@sinonjs/fake-timers', '9.1.2'],
          ['npm', '@types/node-fetch', '2.6.2'],
          ['npm', '@types/uuid', '8.3.4'],
          ['npm', 'algoliasearch', '4.14.2'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'nock', '13.2.9'],
          ['npm', 'node-fetch', '2.6.7'],
          ['npm', 'openapi-enforcer', '1.21.0'],
          ['npm', 'uuid', '8.3.2'],
        ],
      },
      {
        id: 'iyMd6rYJHLDx',
        name: '@algolia/crawler-test-website',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-test-website/package.json',
        ],
        tech: null,
        edges: [],
        inComponent: null,
        childs: [],
        techs: ['express', 'javascript', 'nodejs', 'typescript'],
        languages: { JavaScript: 1, JSON: 2, TypeScript: 8, EJS: 1 },
        dependencies: [
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', 'body-parser', '1.20.0'],
          ['npm', 'compression', '1.7.4'],
          ['npm', 'cookie-parser', '1.4.6'],
          ['npm', 'csurf', '1.11.0'],
          ['npm', 'ejs', '3.1.8'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'serve-index', '1.9.1'],
        ],
      },
      {
        id: 'KHqaWAduwyWj',
        name: '@algolia/crawler-tests',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-tests/package.json',
        ],
        tech: null,
        edges: [
          {
            to: 'kxpOeyjD4KRg',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'kxpOeyjD4KRg',
            name: 'algolia',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-tests/package.json',
            ],
            tech: 'algolia',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['algolia', 'express', 'html', 'nodejs', 'typescript'],
        languages: { HTML: 1, JSON: 2, TypeScript: 12 },
        dependencies: [
          ['npm', '@algolia/crawler-api', '1.0.0'],
          ['npm', '@algolia/crawler-api-public', '1.0.0'],
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@algolia/crawler-manager', '1.0.0'],
          ['npm', '@algolia/crawler-test-website', '1.0.0'],
          ['npm', '@algolia/crawler-web', '1.0.0'],
          ['npm', '@algolia/crawler-worker', '1.0.0'],
          ['npm', 'algoliasearch', '4.14.2'],
          ['npm', 'dotenv', '16.0.1'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'node-fetch', '2.6.7'],
          ['npm', 'server-destroy-vvo', '1.0.1'],
        ],
      },
      {
        id: 'pxvvhlNuO60F',
        name: '@algolia/crawler-web',
        group: 'component',
        path: ['/Users/samuelbodin/code/crawler/src/crawler-web/package.json'],
        tech: null,
        edges: [
          {
            to: 'vyh4p17tohHP',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'dEMDgURbuvcx',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'vyh4p17tohHP',
            name: 'datadog',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-web/package.json',
            ],
            tech: 'datadog',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: 'dEMDgURbuvcx',
            name: 'sqreen',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-web/package.json',
            ],
            tech: 'sqreen',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['datadog', 'express', 'nodejs', 'sqreen', 'typescript'],
        languages: { JSON: 2, TypeScript: 8 },
        dependencies: [
          ['npm', '@algolia/crawler-admin', '0.1.0'],
          ['npm', '@algolia/crawler-api', '1.0.0'],
          ['npm', '@algolia/crawler-api-public', '1.0.0'],
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-test-website', '1.0.0'],
          ['npm', 'body-parser', '1.20.0'],
          ['npm', 'cookie-parser', '1.4.6'],
          ['npm', 'dd-trace', '3.0.0'],
          ['npm', 'express', '4.17.3'],
          ['npm', 'express-session', '1.17.3'],
          ['npm', 'helmet', '5.0.2'],
          ['npm', 'sq-native', '1.0.10'],
          ['npm', 'sqreen', '2.0.1'],
          ['npm', '@types/cookie-parser', '1.4.3'],
          ['npm', '@types/express', '4.17.13'],
          ['npm', '@types/express-session', '1.17.4'],
        ],
      },
      {
        id: 'HD4xAR5zIY8T',
        name: '@algolia/crawler-worker',
        group: 'component',
        path: [
          '/Users/samuelbodin/code/crawler/src/crawler-worker/package.json',
        ],
        tech: null,
        edges: [
          {
            to: 'Mpbhv2Wo2K9g',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
          {
            to: 'LiQH7fWbeQhJ',
            portSource: 'right',
            portTarget: 'left',
            read: true,
            write: true,
            vertices: [],
          },
        ],
        inComponent: null,
        childs: [
          {
            id: 'LiQH7fWbeQhJ',
            name: 'datadog',
            group: 'thirdparty',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-worker/package.json',
            ],
            tech: 'datadog',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
          {
            id: 'Mpbhv2Wo2K9g',
            name: 'rabbitmq',
            group: 'component',
            path: [
              '/Users/samuelbodin/code/crawler/src/crawler-worker/package.json',
            ],
            tech: 'rabbitmq',
            edges: [],
            inComponent: null,
            childs: [],
            techs: [],
            languages: {},
            dependencies: [],
          },
        ],
        techs: ['datadog', 'nodejs', 'rabbitmq', 'typescript'],
        languages: { JSON: 2, TypeScript: 36, 'Jest Snapshot': 2 },
        dependencies: [
          ['npm', '@algolia/crawler-common', '1.0.0'],
          ['npm', '@algolia/crawler-isolated', '1.0.0'],
          ['npm', '@algolia/crawler-manager', '1.0.0'],
          ['npm', 'amqplib', '0.8.0'],
          ['npm', 'dd-trace', '3.0.0'],
          ['npm', '@algolia/crawler-local-setup', '1.0.0'],
          ['npm', '@algolia/crawler-tests', '1.0.0'],
          ['npm', '@types/amqplib', '0.8.2'],
          ['npm', 'dotenv', '16.0.1'],
          ['npm', 'nock', '13.2.9'],
        ],
      },
    ],
    techs: [
      'circleci',
      'css',
      'docker',
      'eslint',
      'github',
      'githubactions',
      'html',
      'javascript',
      'nodejs',
      'prettier',
      'renovate',
      'shell',
      'typescript',
    ],
    languages: {
      YAML: 30,
      Shell: 1,
      JavaScript: 117,
      Markdown: 16,
      JSON: 9,
      CSS: 70,
      HTML: 2373,
      INI: 1,
    },
    dependencies: [
      ['npm', 'db-migrate', '0.11.13'],
      ['npm', 'db-migrate-pg', '1.2.2'],
      ['npm', 'module-alias', '2.2.2'],
      ['npm', '@semantic-release/changelog', '6.0.1'],
      ['npm', '@semantic-release/exec', '6.0.3'],
      ['npm', '@semantic-release/git', '10.0.1'],
      ['npm', '@types/node', '16.11.48'],
      ['npm', '@typescript-eslint/eslint-plugin', '5.20.0'],
      ['npm', '@typescript-eslint/parser', '5.20.0'],
      ['npm', 'concurrently', '7.3.0'],
      ['npm', 'conventional-commits-parser', '3.2.4'],
      ['npm', 'copyfiles', '2.4.1'],
      ['npm', 'dotenv', '16.0.1'],
      ['npm', 'dotenv-safe', '8.2.0'],
      ['npm', 'eslint', '7.32.0'],
      ['npm', 'eslint-config-algolia', '20.0.0'],
      ['npm', 'eslint-config-prettier', '8.5.0'],
      ['npm', 'eslint-import-resolver-alias', '1.1.2'],
      ['npm', 'eslint-plugin-algolia', '2.0.0'],
      ['npm', 'eslint-plugin-chai-friendly', '0.7.2'],
      ['npm', 'eslint-plugin-cypress', '2.12.1'],
      ['npm', 'eslint-plugin-eslint-comments', '3.2.0'],
      ['npm', 'eslint-plugin-import', '2.26.0'],
      ['npm', 'eslint-plugin-jest', '26.8.2'],
      ['npm', 'eslint-plugin-jsdoc', '39.3.6'],
      ['npm', 'eslint-plugin-jsx-a11y', '6.6.1'],
      ['npm', 'eslint-plugin-prettier', '4.2.1'],
      ['npm', 'eslint-plugin-react', '7.30.1'],
      ['npm', 'eslint-plugin-react-hooks', '4.6.0'],
      ['npm', 'husky', '8.0.1'],
      ['npm', 'jest', '28.1.3'],
      ['npm', 'jest-circus', '28.1.3'],
      ['npm', 'jest-cli', '28.1.3'],
      ['npm', 'jest-junit', '14.0.0'],
      ['npm', 'json', '11.0.0'],
      ['npm', 'lint-staged', '13.0.3'],
      ['npm', 'nodemon', '2.0.19'],
      ['npm', 'prettier', '2.6.2'],
      ['npm', 'renovate-config-algolia', '2.1.10'],
      ['npm', 'semantic-release', '19.0.3'],
      ['npm', 'ts-jest', '28.0.8'],
      ['npm', 'ts-node', '10.9.1'],
      ['npm', 'typescript', '4.7.4'],
    ],
  },
  {
    id: 'XHNNrphS3ZRK',
    name: 'db',
    group: 'component',
    path: ['/Users/samuelbodin/code/crawler/docker-compose.yml'],
    tech: 'postgresql',
    edges: [],
    inComponent: null,
    childs: [],
    techs: [],
    languages: {},
    dependencies: [['docker', 'postgres', '14.5-alpine']],
  },
  {
    id: 'MlxonSmjhVaV',
    name: 'elasticsearch',
    group: 'component',
    path: ['/Users/samuelbodin/code/crawler/docker-compose.yml'],
    tech: 'elasticsearch',
    edges: [],
    inComponent: null,
    childs: [],
    techs: [],
    languages: {},
    dependencies: [['docker', 'elasticsearch', '7.17.5']],
  },
  {
    id: 'B1V4cgPujjki',
    name: 'kibana',
    group: 'component',
    path: ['/Users/samuelbodin/code/crawler/docker-compose.yml'],
    tech: 'kibana',
    edges: [],
    inComponent: null,
    childs: [],
    techs: [],
    languages: {},
    dependencies: [['docker', 'kibana', '7.17.5']],
  },
  {
    id: 'op3KEL3lw3PB',
    name: 'rabbitmq',
    group: 'component',
    path: ['/Users/samuelbodin/code/crawler/docker-compose.yml'],
    tech: 'rabbitmq',
    edges: [],
    inComponent: null,
    childs: [],
    techs: [],
    languages: {},
    dependencies: [['docker', 'rabbitmq', '3.10.7-management-alpine']],
  },
  {
    id: '90uaaV0QPN2D',
    name: 'redis',
    group: 'component',
    path: ['/Users/samuelbodin/code/crawler/docker-compose.yml'],
    tech: 'redis',
    edges: [],
    inComponent: null,
    childs: [],
    techs: [],
    languages: {},
    dependencies: [['docker', 'redis', '7.0.4-alpine']],
  },
  {
    id: '8MpDS7m3KbkN',
    name: 'renderscript',
    group: 'component',
    path: ['/Users/samuelbodin/code/crawler/docker-compose.yml'],
    tech: null,
    edges: [],
    inComponent: null,
    childs: [],
    techs: [],
    languages: {},
    dependencies: [['docker', 'algolia/renderscript', '2.1.16']],
  },
  {
    id: 'OPaXj3FQmzCF',
    name: 'tika',
    group: 'component',
    path: ['/Users/samuelbodin/code/crawler/docker-compose.yml'],
    tech: null,
    edges: [],
    inComponent: null,
    childs: [],
    techs: [],
    languages: {},
    dependencies: [['docker', 'apache/tika', '1.28.4']],
  },
];
