name: Renovate
on:
  schedule:
    - cron: '0 14 1 * 4'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Renovate Automatic Branch
        uses: bodinsamuel/renovate-automatic-branch@v1
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          repo-owner: specfy
          repo-name: specfy
          branch-base: main
